K-allagbe/issue3-integrate-azure-cognitive-search
ai-cfia/finesse-backend pull request #4
Opened 2023-11-17 14:35 UTC by k-allagbe

Closes #3 : Integrate azure cognitive search

2023-11-20 15:14 UTC, k-allagbe commented on todo.md
> +# Azure Cognitive Search Integration
It's personal and wasn't supposed to be included in the PR. There's already a higher level task description in the issue.

2023-11-20 15:15 UTC, k-allagbe commented on assets/finesse-component-diagram.puml
> +@enduml
Done

2023-11-20 15:19 UTC, k-allagbe commented on assets/finesse-component-diagram.puml
> +@startuml Finesse component diagram
It's in the root. I've seen stuff that are meant to be used in markdowns be stored in an "assets" folder before. But It's all the same to me. I'll put this in the readme along with the project documentation.

2023-11-20 15:34 UTC, k-allagbe commented on tests/test_azure_search.py
> +
Will fix this with postgres/azure output uniformization.

2023-11-20 20:20 UTC, k-allagbe commented on tests/test_azure_search.py
> +
Done with mocks.

2023-11-21 21:35 UTC, rngadam requested changes
let's address the CodeQL warning; only developers overriding this in their local dev environment should have this turned on.

2023-11-21 21:35 UTC, rngadam commented on app/__init__.py
> +    app.run(debug=True)
@k-allagbe we probably want to make this an environment variable that defaults to False when not present to guarantee we don't push code that runs in debug mode.

2023-11-22 07:33 UTC, k-allagbe commented on app/__init__.py
> +    app.run(debug=True)
Done

2023-11-22 14:22 UTC, rngadam commented on app/__init__.py
> +    app.run(debug=True)
In the latest version of your code, the __main__ has disappeared completely, is that normal?

2023-11-22 15:05 UTC, k-allagbe commented on app/__init__.py
> +    app.run(debug=True)
I removed it because I thought it not necessary. But for completeness, I added it back so we should be able to run the app with `python run.py`.

2023-11-22 15:10 UTC, rngadam commented on app/__init__.py
> +    app.run(debug=True)
ok, is the DEBUG flag taken into account then? because I see you also don't pass it on as a parameter

2023-11-22 15:23 UTC, k-allagbe commented on app/__init__.py
> +    app.run(debug=True)
Yes and tested. This is current behaviour:
- flask run: runs with debug off. needs to specify --debug to enable it.
- python run.py: depends on the env var
- gunicorn app:app: debug off.

2023-11-22 20:11 UTC, rngadam commented on app/__init__.py
> +    app.run(debug=True)
awesome, thanks. I see the README.md is rather sparse. could we add how to install/run information locally with the note about debugging?

2023-11-22 20:11 UTC, rngadam requested changes
update the README.md with some notes suitable for a first time user/developer.

2023-11-22 20:30 UTC, RussellJimmies approved these changes
Very neat! I'll come and pick your brain for the implementation of the Blueprint on Nachet-Backend.

2023-11-23 01:02 UTC, k-allagbe commented on app/__init__.py
> +    app.run(debug=True)
Done.

2023-11-23 01:04 UTC, k-allagbe commented
> Very neat! I'll come and pick your brain for the implementation of the Blueprint on Nachet-Backend.

Sure. I copied myself from https://github.com/ai-cfia/louis-backend

2023-11-23 19:14 UTC, rngadam commented on app/__init__.py
> +    app.run(debug=True)
Thanks! 

Up to you, but seems like we should be renaming API.md USAGE.md?

2023-11-23 21:15 UTC, k-allagbe commented on app/__init__.py
> +    app.run(debug=True)
Yes it is more coherent. Done.

2023-11-24 13:48 UTC, rngadam approved these changes

2023-11-24 13:48 UTC, rngadam commented
Looks great, thanks!!

2023-11-24 13:49 UTC, merged