issue #1: ailab search endpoint and tests
ai-cfia/finesse-backend pull request #8
Opened 2023-11-28 14:40 UTC by k-allagbe

Closes #1: Integrate ailab search

- [X] implementation
- [X] manual tests
- [X] unit tests

2023-11-28 20:12 UTC, rngadam commented on .env.template
> +# Example: louis_v005
louis_0.0.5

2023-11-28 20:28 UTC, rngadam requested changes

2023-11-28 20:28 UTC, rngadam commented on .env.template
> +# Example: louis_v005
https://github.com/ai-cfia/dev-rel-docs/pull/77/files

2023-11-29 13:12 UTC, k-allagbe commented on .env.template
> +# Example: louis_v005
Done.

2023-11-29 16:32 UTC, rngadam approved these changes

2023-11-29 16:50 UTC, RussellJimmies approved these changes

2023-11-29 20:11 UTC, merged